**Actividad 2.1 (Extracción de Datos)**

In [1]:
#Import the libraries to work with data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#load from a .xlsx file without index
df = pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
df

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

**_FILTROS BASICOS PARA VARIABLES CUALITATIVAS_**

In [38]:
#Filter by object
filterObject = df[(df["NOMBRE_VENDEDOR"] == "LETICIA RAMIREZ HERNANDEZ")]
filterObject

#Descripcion: filtramos la variable-columna NOMBRE_VENDEDOR y devuelve solo las filas 
#que son TRUE respecto a LETICIA RAMIREZ HERNANDEZ

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1416,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,3,PJ31Q1G1A400,"TER J 3/16""ØX1/2"" EXT3MT MALLA INOX Z/E",439.15,0.00,123.21,1317.45,369.62,315.94,947.83
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49

In [41]:
#Filter by rows
#filter2 = df.iloc[3:10,:]  #Filas consecutivas
filterByRows = df.iloc[[2,5] , :]  #Filas no consecutivas
filterByRows

#Decripcion: Filtramos las filas 2 y 5, pues usamos el codigo de filas no consecutivas

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32

In [42]:
#Filter by columns
filterByColumns = df.iloc[ : , 1:3] #Columnas consecutivas
#filter3 = df.iloc[ : , [1,4,6]] #Columnas no consecutivas
filterByColumns

#Descripcion: Filtramos las columnas consecutivas de la primera a la tercera (INDEX, FECHA_DOC, NOMBRE_VENDEDOR)

      FECHA_DOC            NOMBRE_VENDEDOR
0    2022-01-05  LETICIA RAMIREZ HERNANDEZ
1    2022-01-05  LETICIA RAMIREZ HERNANDEZ
2    2022-01-05   DIEGO ARMANDO LEON DURAN
3    2022-01-05   DIEGO ARMANDO LEON DURAN
4    2022-01-05  LETICIA RAMIREZ HERNANDEZ
...         ...                        ...
1421 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1422 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1423 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1424 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1425 2022-12-23         AARON NUÑO CORDOVA

[1426 rows x 2 columns]

In [43]:
#Carga desde un archivo .xlsx con indice
df1 = pd.read_excel('Detalle precios y productos fabricados 2022.xlsx', index_col=0)
df1

,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
CVE_DOC,,,,,,,,,,,,,
F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...
F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [44]:
#Paso 2: Aplicamos filtro de filas vs columnas
filterRowsVSColumns = df1.loc[["F39834", "F37043", "F37041"], ["NOMBRE_CLIENTE", "MARGEN_TOTAL_CALCULADO"]]
filterRowsVSColumns

#Descripcion: Filtramos las filas que tengan "F39834", "F37043", "F37041" contra las columnas
#que se llamen "NOMBRE_CLIENTE", "MARGEN_TOTAL_CALCULADO"

                    NOMBRE_CLIENTE  MARGEN_TOTAL_CALCULADO
CVE_DOC
F39834   LUIS ENRIQUE PATIÑO PEREZ                 3658.12
F39834   LUIS ENRIQUE PATIÑO PEREZ                 3683.48
F37043          PÚBLICO EN GENERAL                  141.41
F37043          PÚBLICO EN GENERAL                  375.32
F37041   ANA BARBARA CRUZ PALACIOS                 2617.56

In [45]:
#Filter 5
filterHEAD = df.head(10)  #muestra los primeros 10 registros
filterHEAD

#Descripcion: Filtramos los primeros 10 registros tomando en cuenta las filas

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11

In [46]:
#Filtro 6
filterTAIL = df.tail(2)  #muestra los 5 ultimos registros
filterTAIL

#Description: Filtramos los ultimos dos registros

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

**_FILTROS BASICOS PARA VARIABLES CUANTITATIVAS_**

In [47]:
#Filter by comparison
filterByComparison = df[df["MARGEN_TOTAL_CALCULADO"] > 7000]
filterByComparison

#Descripcion: Filtramos la columna MARGEN_TOTAL_CALCULADO que tenga registros mayores a 7000

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
29,F37078,2022-01-07,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.60,9163.18,993.88,29816.42
31,F37086,2022-01-10,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.60,9163.18,993.88,29816.42
38,F37098,2022-01-12,DIEGO ARMANDO LEON DURAN,REDYPLAST,40,CBS00045,"CART INOX 3/8""Øx8"" 340W, 220V CABLE 35CM",259.60,64.85,64.85,10384.00,2594.17,194.75,7789.83
40,F37102,2022-01-12,ALFREDO CANELA,DEACERO,3,TUE00321,"TUB INOX 1/2""ØX1030MMX980MM 3KW480V ""L""",12720.00,0.00,1509.14,38160.00,4527.42,11210.86,33632.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1409,F39816,2022-12-22,ALFREDO CANELA,TOSTADAS FANNY,6,TUA00492,"TUB INOX 1/2""ØX40CM 4000W 220V ""M"" BUSH",2959.68,0.00,1186.76,17758.08,7120.54,1772.92,10637.54
1412,F39824,2022-12-23,ALFREDO CANELA,MEGO AFEK,1,TUA00325,"TUB INOX 1/2""ØX75CM ""U"" 30KW440V BRIDA6""",12500.00,4579.08,4579.08,12500.00,4579.08,7920.92,7920.92
1413,F39826,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,5,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1897.27,78.09,78.09,9486.35,390.43,1819.18,9095.92
1415,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,6,BP00006,BAN P INOX 1800x25mm 2800W 440V. CABLE,1888.00,0.00,294.50,11328.00,1767.02,1593.50,9560.98
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

**_FILTROS BASICOS CON CONETORES LOGICOS_**

In [48]:
#Filter AND
filterAND = df[(df["PRECIO_UNITARIO"] < 2500) & (df["CVE_ART"] == "BOBINA001")]
filterAND

#Description: Filtramos la columna PRECIO_UNITARIO que tenga registros menores a 2500 y al mismo tiempo
# filtramos la columna CVE_ART que tenga registros igual a BOBINA001

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
29,F37078,2022-01-07,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.6,9163.18,993.88,29816.42
31,F37086,2022-01-10,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,305.44,305.44,38979.6,9163.18,993.88,29816.42
403,F37777,2022-03-31,ALFREDO CANELA,CLAVOS NACIONALES C.N,60,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,340.80,340.80,77959.2,20448.01,958.52,57511.19
666,F38344,2022-06-09,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,378.12,378.12,38979.6,11343.64,921.20,27635.96
832,F38638,2022-07-21,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,429.81,429.81,38979.6,12894.24,869.51,26085.36
907,F38797,2022-08-11,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,430.03,430.03,38979.6,12900.92,869.29,26078.68

In [49]:
#Filter OR
filterOR = df[(df["NOMBRE_VENDEDOR"] == "DIEGO ARMANDO LEON DURAN") | (df["CVE_ART"] == "BOBINA001")]
filterOR

#Description: Filtramos la columna NOMBRE_VENDEDOR que tenga registros iguales a DIEGO ARMANDO LEON DURAN o
# filtramos la columna CVE_ART que tenga registros igual a BOBINA001

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,F38459,2022-06-24,DIEGO ARMANDO LEON DURAN,MEXICANA DE INGENIERIA Y MAQUINARIA,3,CAE00011,"CAE 9.4MMØx2""LONG ESC90°150W 220V Ext22""",375.00,0.00,122.35,1125.00,367.04,252.65,757.96
832,F38638,2022-07-21,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,429.81,429.81,38979.60,12894.24,869.51,26085.36
851,F38665,2022-07-26,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,0.00,277.50,14000.00,277.50,13722.50,13722.50
907,F38797,2022-08-11,ALFREDO CANELA,CLAVOS NACIONALES C.N,30,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,430.03,430.03,38979.60,12900.92,869.29,26078.68
1296,F39592,2022-11-16,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,0.00,277.50,14000.00,277.50,13722.50,13722.50

In [50]:
#Filter NOT
filterNOT = df[~(df["CVE_DOC"] == "F39834")]
filterNOT

#Description: filtramos la columna CVE_DOC que no tenga el registro igual a F39834

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BN00146,"BAN INOX 9""ØX3"" ANCH 1700W 230V T/CABLE",2020.42,421.91,421.91,4040.84,843.82,1598.51,3197.02
1420,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,PT00079,PT-100 7.5MMØX95MM EXT.48CM 3H C/MACHO,1177.07,477.16,477.16,2354.14,954.32,699.91,1399.82
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [51]:
#Convertir archivo filtrado a CSV
filterObject.to_csv("filterByObject.csv")
filterByRows.to_csv("filterByRows.csv")
filterByColumns.to_csv("filterByColumns.csv")
filterRowsVSColumns.to_csv("filterRowsVSColumns.csv")
filterHEAD.to_csv("filterHEAD.csv")
filterTAIL.to_csv("filterTAIL.csv")
filterByComparison.to_csv("filterByComparison.csv")
filterAND.to_csv("filterAND.csv")
filterOR.to_csv("filterOR.csv")
filterNOT.to_csv("filterNOT.csv")